---
- name: read configuration from previous provisioning
  slurp:
    src: "{{ ustreamer_saved_settings_file }}"
  register: ustreamer_saved_settings_slurp

- name: decode provisioning config
  set_fact:
      ustreamer_saved_settings: "{{ ustreamer_saved_settings_slurp['content'] | b64decode | from_yaml }}"

- name: read ustreamer_capture_device from config file if it's not already defined
  set_fact:
    ustreamer_capture_device: "{{ ustreamer_saved_settings['capture_device'] if ustreamer_capture_device == None and 'capture_device' in ustreamer_saved_settings else ustreamer_capture_device }}"
  when: ustreamer_capture_device == None
