---
- name: reload systemd config
  systemd:
    daemon_reload: yes

- name: restart uStreamer
  service:
    name: ustreamer
    state: restarted

- name: load TC358743 EDID file
  service:
    name: load-tc358743-edid
    state: started
